### ISSUE TITLE
"Wait for geolocation" does not get removed after geolocation is accuired

### ISSUE THREAD

**Issue by WallyDoodlez** [ffwdme/ffwdme.js#1]
I tired opening the dev demo on dev.ffwdmejs.org on my windows phone 8.1 and the "Wait for Geolocation" overlay does not go away after the map has centered to current location

**Comment by fabrik42** [comment]
Hi!

Thank you for your report, I'm trying to elaborate a bit here and hopefully I can help you.

First of all, the dev.ffwdmejs.org demo is not really meant to be used with mobile devices. It's more of a debugging playground for local development on the desktop. However, in general it should work on mobile devices too.

I don't have a windows phone at hand, but I can try to make a couple of assumptions:

I guess the win mobile 8.1 browser can utilize the geoposition, because leaflet (the map) uses it too and it centers the map. ffwdme itself has its own listener on the geoposition and emits its own events, once the geoposition is aquired. In this case, the following happens:

``` javascript
ffwdme.on('geoposition:ready', function() {
  console.info("Received initial geoposition!");
  $('#loader').remove();
});
```

So my first guess would be that your browser does not support the `console.info` interface and therefore raises an error before it can remove the loader element.

I'm currently working on a mobile optimized standalone demo for the lib so people can try it out on their mobile devices.

**Comment by fabrik42** [comment]
Closing this for now. Please reopen if there is anything new to report.

Cheers,
Christian
