### ISSUE TITLE
Calling `stop` or `reset` on `ffwdme.navigation` does not clear current route.

### ISSUE THREAD

**Issue by adamduren** [ffwdme/ffwdme.js#14]
I've been looking through the docs and source code of this lib and am trying to figure out how to reset a map to its initial state after navigation had started. I thought that either of the two methods mentioned in the title might be where that would happen but it does not appear so. Does the library support this functionality?

If so I would be willing to add some documentation otherwise a new feature to support this.

**Comment by fabrik42** [comment]
At the moment `stop` just emits an event. It's not really used.

The `reset` method resets the internal state of the navigation object and is used if you want to replace the route handled by the navigation event (e.g. if you do a rerouting, because the user left the calculated route).

I would be very happy to accept contributions, let me know if you have further questions.

Cheers,

Christian
