### ISSUE TITLE
How to implement this into xampp or phoneGAP server.?

### ISSUE THREAD

**Issue by buddhishan** [ffwdme/ffwdme.js#16]
The source code ffwdme.js is perfectly working on gulp server. I'm creating a mobile application using phoneGAP and Cordova. There I want this ffwdme.js code to be working on PhoneGAP server.  I Have only a little knowledge of javascript. Please help me. Thank you in advance.

**Comment by fabrik42** [comment]
Sorry, I don't have much experience with Cordova/Phonegap, so I'm afraid I can't help you very much.

A wild guess: 

You don't need to put the whole `ffwdme` directory into your Phonegap project.
The gulp server of this project is only meant for local development. Once you are ready to use your lib somewhere else (e.g. in your Phonegap project), you have to run the `gulp build` task in order to export the lib into simple JS/CSS files. A new directory called `build` should be generated that contains these files.

Take the generated files and use them in your Phonegap project like any other JS/CSS files :)

Hope this helps!

**Comment by buddhishan** [comment]
HI,
It worked fine!. Thanks. Can you further explain me about the files I need
to modify in order to have my own routes and to have real time navigation
on my own route.? Files are very lengthy and it's been very difficult to
understand because of my lack of expertise.

Thank you

On Fri, Mar 18, 2016 at 9:59 PM, Christian Bäuerlein <
notifications@github.com> wrote:

> Sorry, I don't have much experience with Cordova/Phonegap, so I'm afraid I
> can't help you very much.
> 
> A wild guess:
> 
> You don't need to put the whole ffwdme directory into your Phonegap
> project.
> The gulp server of this project is only meant for local development. Once
> you are ready to use your lib somewhere else (e.g. in your Phonegap
> project), you have to run the gulp build task in order to export the lib
> into simple JS/CSS files. A new directory called build should be
> generated that contains these files.
> 
> Take the generated files and use them in your Phonegap project like any
> other JS/CSS files :)
> 
> Hope this helps!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ffwdme/ffwdme.js/issues/16#issuecomment-198438245

## 
- ```
  Buddhishan Manamperi*
  ```
  
    _Director Finance, Project Lead - CycleMate_
    TEAMREGEL
    Mobile : (+94)\* 77 3683072\*  |  email :  buddhishan.rc@gmail.com | b
  sithiraweeratunga@ymail.comuddhishan@teamregel.com
    Website : w http://www.aiesec.org/ww.teamregel.com
  
    My public profiles :  [image: Facebook]
  https://www.facebook.com/public/Buddhishan-Manamperi
  https://www.facebook.com/dehan.vithana[image: LinkedIn]
  https://lk.linkedin.com/in/buddhishan

**Comment by fabrik42** [comment]
Hmm sorry, but you need to be a little bit more precise. What is your current problem/which files do you not understand?

Best,
Christian

**Comment by fabrik42** [comment]
Closing this for now. Please reopen, if there is anything you need to know.
