### ISSUE TITLE
use json instead of jsonp for GraphHopper

### ISSUE THREAD

**Issue by karussell** [ffwdme/ffwdme.js#40]
See discussion https://github.com/graphhopper/graphhopper/issues/1375

Necessary changes:

https://github.com/ffwdme/ffwdme.js/blob/master/src/core/routing/graph_hopper.js#L64

and the proxy needs a bigger change:

https://github.com/ffwdme/ffwdme.js/blob/master/src/core/utils/proxy.js#L56

For that one could use https://github.com/visionmedia/superagent 
(we use this in [our JS client](https://github.com/graphhopper/directions-api-js-client) for ajax fetching without jquery)

**Comment by fabrik42** [comment]
Hi Peter,
thank you for the reminder, I will make the changes over the weekend!

Best,
Christian

**Comment by fabrik42** [comment]
Hi Peter,

after lots of consideration I decided to not update the API, but instead deprecate the project.

I personally did not use if for years and it is already pretty outdated. Right now, I lack the time and motivation to revive the project. Additionally, the project was taken over by flinc in 2012, so I provide support here in my free time, even though I don't own the project anymore and don't even work for the company anymore. 

Peter you were an early and steady supporter of ffwdme and I will always be grateful for that! I hope our ways cross again, maybe with some other projects. 

Please don't hold back API changes at GraphHopper because of this project.

Cheers,
Christian

**Comment by karussell** [comment]
Thanks Christian for the update and completely understand your decision! 

> Please don't hold back API changes at GraphHopper because of this project

Yeah, highly likely we have to break the usage for ffwdme as `jsonp` is not used from others and we don't want to support it further.

Thanks for making ffwdme possible and see you elsewhere :)
