### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by arkangelx** [ffwdme/ffwdme.js#7]
Hi I am trying to build an android app that records a route that a user is following, then replay that the route for another user to follow. I have been able to successfully create the route and save the geo points to a database.   I am trying to figure out how to send  this data to the ffwdme to replay this route in ffwdme, given that I would be providing a list of predefined geopoints

**Comment by fabrik42** [comment]
Hi!

Yes you can do this. By default ffwdme works with the Graphhopper API, but instead of calculating directions, you could also provide your own.

You can do this by implementing your own sublcass of the `ffwdme.routing.Base` class https://github.com/ffwdme/ffwdme.js/blob/master/src/core/routing/base.js

If you call it `ffwdme.routing.MyRouting` you can pass it to the initializer like this:

``` javascript
  ffwdme.initialize({
    routing: 'MyRouting'
  });
```

Your own subclass has to do the following:
- implement a method `fetch()` that get called by the framework if a new route is needed.
- The `fetch()` method needs to trigger a `start` event, like here https://github.com/ffwdme/ffwdme.js/blob/master/src/core/routing/graph_hopper.js#L86
- It needs to load the route from somewhere (e.g. the database)
- If this does not work, it needs to call the `error` method
- If it does work, it needs to convert your route in a `ffwdme.Route` object and call the `success` method. see https://github.com/ffwdme/ffwdme.js/blob/master/src/core/route.js

I think a good starting point is the implementation of the Graphhopper service:
https://github.com/ffwdme/ffwdme.js/blob/master/src/core/routing/graph_hopper.js#L54-L146

Also, have a look at the specs - they should help you to see the basic structure of a route:
https://github.com/ffwdme/ffwdme.js/blob/master/spec/fixtures/route_response_simplified.json
https://github.com/ffwdme/ffwdme.js/blob/8db4c7721f253211eadddffca7bf83c23f65874e/spec/core/route_spec.js

Let me know, if this works out for you!

Cheers,
Christian

**Comment by arkangelx** [comment]
Thanks so much. I'll look into it

On Sun, Sep 13, 2015 at 8:57 AM, Christian Bäuerlein <
notifications@github.com> wrote:

> Hi!
> 
> Yes you can do this. By default ffwdme works with the Graphhopper API, but
> instead of calculating directions, you could also provide your own.
> 
> You can do this by implementing your own sublcass of the
> ffwdme.routing.Base class
> https://github.com/ffwdme/ffwdme.js/blob/master/src/core/routing/base.js
> 
> If you call it ffwdme.routing.MyRouting you can pass it to the
> initializer like this:
> 
>   ffwdme.initialize({
>     routing: 'MyRouting'
>   });
> 
> Your own subclass has to do the following:
> - implement a method fetch() that get called by the framework if a new
>   route is needed.
> - The fetch() method needs to trigger a start event, like here
>   https://github.com/ffwdme/ffwdme.js/blob/master/src/core/routing/graph_hopper.js#L86
> - It needs to load the route from somewhere (e.g. the database)
> - If this does not work, it needs to call the error method
> - If it does work, it needs to convert your route in a ffwdme.Route
>   object and call the success method. see
>   https://github.com/ffwdme/ffwdme.js/blob/master/src/core/route.js
> 
> I think a good starting point is the implementation of the Graphhopper
> service:
> 
> https://github.com/ffwdme/ffwdme.js/blob/master/src/core/routing/graph_hopper.js#L54-L146
> 
> Also, have a look at the specs - they should help you to see the basic
> structure of a route:
> 
> https://github.com/ffwdme/ffwdme.js/blob/master/spec/fixtures/route_response_simplified.json
> 
> https://github.com/ffwdme/ffwdme.js/blob/8db4c7721f253211eadddffca7bf83c23f65874e/spec/core/route_spec.js
> 
> Let me know, if this works out for you!
> 
> Cheers,
> Christian
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ffwdme/ffwdme.js/issues/7#issuecomment-139849793.

## 

Innovate & Prevail

**Comment by arkangelx** [comment]
Is hosting the javascript lib on a server the best approach or loading it
locally from the device

On Sun, Sep 13, 2015 at 10:25 AM, Samson Akisanya <info@mobileparadigm.co.uk

> wrote:
> 
> Thanks so much. I'll look into it
> 
> On Sun, Sep 13, 2015 at 8:57 AM, Christian Bäuerlein <
> notifications@github.com> wrote:
> 
> > Hi!
> > 
> > Yes you can do this. By default ffwdme works with the Graphhopper API,
> > but instead of calculating directions, you could also provide your own.
> > 
> > You can do this by implementing your own sublcass of the
> > ffwdme.routing.Base class
> > https://github.com/ffwdme/ffwdme.js/blob/master/src/core/routing/base.js
> > 
> > If you call it ffwdme.routing.MyRouting you can pass it to the
> > initializer like this:
> > 
> >   ffwdme.initialize({
> >     routing: 'MyRouting'
> >   });
> > 
> > Your own subclass has to do the following:
> > - implement a method fetch() that get called by the framework if a
> >   new route is needed.
> > - The fetch() method needs to trigger a start event, like here
> >   https://github.com/ffwdme/ffwdme.js/blob/master/src/core/routing/graph_hopper.js#L86
> > - It needs to load the route from somewhere (e.g. the database)
> > - If this does not work, it needs to call the error method
> > - If it does work, it needs to convert your route in a ffwdme.Route
> >   object and call the success method. see
> >   https://github.com/ffwdme/ffwdme.js/blob/master/src/core/route.js
> > 
> > I think a good starting point is the implementation of the Graphhopper
> > service:
> > 
> > https://github.com/ffwdme/ffwdme.js/blob/master/src/core/routing/graph_hopper.js#L54-L146
> > 
> > Also, have a look at the specs - they should help you to see the basic
> > structure of a route:
> > 
> > https://github.com/ffwdme/ffwdme.js/blob/master/spec/fixtures/route_response_simplified.json
> > 
> > https://github.com/ffwdme/ffwdme.js/blob/8db4c7721f253211eadddffca7bf83c23f65874e/spec/core/route_spec.js
> > 
> > Let me know, if this works out for you!
> > 
> > Cheers,
> > Christian
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ffwdme/ffwdme.js/issues/7#issuecomment-139849793.
> 
> ## 
> 
> Innovate & Prevail

## 

Innovate & Prevail

**Comment by fabrik42** [comment]
This depends, I guess...
The best solution would be to host it on the server and cache it on the client unless there is an update available. Maybe an application cache could be useful for you http://www.html5rocks.com/en/tutorials/appcache/beginner/

**Comment by fabrik42** [comment]
closing this for now - let me know if there is anything else you need help with
